FROM node:20

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
WORKDIR /app/frontend
RUN npm install next react react-dom @apollo/client graphql
CMD ["npx", "next", "dev", "-p", "3000"]